<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An error occurred while installing the Image module.' => '',
  'Congratulations!' => '',
  'Continue &raquo;' => '',
  'Do you wish to continue?' => '',
  'Error' => '',
  'Install' => '',
  'No' => '',
  'Please try again or consult the documentation.' => '',
  'Reinstall' => '',
  'The Image module has been installed successfully.' => '',
  'The Image module is already installed!' => '',
  'This will install the Image module.' => '',
  'WARNING: All your existing data will be lost.' => '',
  'Yes' => '',
);
